matplotlib
this is a sample code i have seen working else where so the cod eis not the issue its probably my system.  i get the following error:

Traceback (most recent call last):

  File "<ipython-input-2-1d7044f7b337>", line 16, in <module>
    cfd.plot()

  File "C:\Users\souan\Anaconda3\lib\site-packages\nltk\probability.py", line 1910, in plot
    'The plot function requires matplotlib to be installed.'

ValueError: The plot function requires matplotlib to be installed.See http://matplotlib.org/